# Travis CI configuration file for running tests
sudo: false
language: python
branches:
    only:
      - master
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - pep8 .
  - pylint android
  - pylint ios
  - pylint common
